const CARD=[
    {
        id:'1',
        url:require('../Images/download(1).jpeg'),
        title:'Pizza Wings',
        img:require('../Images/star.png'),
        uri:require('../Images/right-arrow(1).png'),
        pro:'Promoted',
        fav:require('../Images/heart.png'),
        left:require('../Images/right-arrow(2).png'),
        arrival:'39 mins | 7 km',
        offer1:'15% OFF  ',
        offer2:'Up to rs 35',
        dis:require('../Images/discount.png'),
        loc:'Fast Food',
        price:'rs 250 for one',
        saf:'Follow all Max Safety measures to ensure your food is safe'
    },
    {
        id:'2',
        url:require('../Images/download(2).jpeg'),
        title:'Hotel Ambros',
        img:require('../Images/star.png'),
        fav:require('../Images/heart.png'),
        uri:require('../Images/right-arrow(1).png'),
        left:require('../Images/right-arrow(2).png'),
        pro:'Promoted',
        arrival:'39 mins | 7 km',
        offer1:'15% OFF',
        offer2:'Up to rs 35',
        dis:require('../Images/discount.png'),
        loc:'Fast Food',
        price:'rs 250 for one',
        saf:'Follow all Max Safety measures to ensure your food is safe'
    },
    {
        id:'3',
        url:require('../Images/download(3).jpeg'),
        title:'Bingo (Parinary Garden)',
        img:require('../Images/star.png'),
        fav:require('../Images/heart.png'),
        uri:require('../Images/right-arrow(1).png'),
        left:require('../Images/right-arrow(2).png'),
        pro:'Promoted',
        arrival:'39 mins | 7 km',
        offer1:'10% OFF',
        offer2:'Up to rs 35',
        dis:require('../Images/discount.png'),
        loc:'Fast Food',
        price:'rs 250 for one',
        saf:'Follow all Max Safety measures to ensure your food is safe'
    },
    {
        id:'4',
        url:require('../Images/download(4).jpeg'),
        title:'A Emporter',
        fav:require('../Images/heart.png'),
        img:require('../Images/star.png'),
        uri:require('../Images/right-arrow(1).png'),
        left:require('../Images/right-arrow(2).png'),
        pro:'Promoted',
        arrival:'39 mins | 7 km',
        offer1:'15% OFF',
        offer2:'Up to rs 35',
        dis:require('../Images/discount.png'),
        loc:'Fast Food',
        price:'rs 250 for one',
        saf:'Follow all Max Safety measures to ensure your food is safe'
   
    },
    {
        id:'5',
        url:require('../Images/download(1).jpeg'),
        title:'Hungry Hub',
        fav:require('../Images/heart.png'),
        img:require('../Images/star.png'),
        uri:require('../Images/right-arrow(1).png'),
        left:require('../Images/right-arrow(2).png'),
        pro:'Promoted',
        arrival:'39 mins | 7 km',
        offer1:'30% OFF ',
        offer2:'Up to rs 35',
        dis:require('../Images/discount.png'),
        price:'rs 250 for one',
        loc:'Fast Food',
        saf:'Follow all Max Safety measures to ensure your food is safe'
    },]
    export default CARD